AWSTemplateFormatVersion: 2010-09-09
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: "dmeszaro-cloudformationtest"

# a lambda function
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          exports.handler = function(event, context) {
            console.log("Hello from Lambda!");
          };
      Handler: index.handler
      Role: !GetAtt MyLambdaFunctionRole.Arn
      Runtime: nodejs18.x


  # Lambda function that gets the current date and time and returns it
  LambdaTime:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          exports.handler = function(event, context) {
            var date = new Date();
            var time = date.toISOString();
            console.log(time);
          };
      Handler: index.handler
      Role: !GetAtt MyLambdaFunctionRole.Arn
      Runtime: nodejs18.x

  # execution role for the lambda function called MyLambdaFunctionRole
  MyLambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*